// It's preferable to keep your action types together.
export const SELECTED_IMAGE = 'SELECTED_IMAGE';
export const FLICKR_IMAGES_SUCCESS = 'FLICKR_IMAGES_SUCCESS';
export const SELECTED_VIDEO = 'SELECTED_VIDEO';
export const SHUTTER_VIDEOS_SUCCESS = 'SHUTTER_VIDEOS_SUCCESS';
export const SEARCH_MEDIA_REQUEST = 'SEARCH_MEDIA_REQUEST';
export const SEARCH_MEDIA_SUCCESS = 'SEARCH_MEDIA_SUCCESS';
export const SEARCH_MEDIA_ERROR = 'SEARCH_MEDIA_ERROR';
// Action for LogIn User
export const REQ_LOGIN_ACTION = 'REQ_LOGIN_ACTION';
export const LOGIN_ACT_SUCCESS = 'LOGIN_ACT_SUCCESS';
export const LOGIN_ACT_ERROR = 'LOGIN_ACT_ERROR';
export const AUTHENTICATED = 'AUTHENTICATED';
export const AUTHENTICATE_ERROR = 'AUTHENTICATE_ERROR';
// Action for Register User
export const REQ_REGISTER_USER = 'REQ_REGISTER_USER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
// Action logout user
export const REQ_LOGOUT_USER = 'REQ_LOGOUT_USER';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';
